apiVersion: v1
kind: Service
metadata:
  labels:
    service: kafka-service
  name: kafka-service
spec:
  ports:
  - name: "29092"
    port: 29092
    targetPort: 29092
    nodePort: 30009
  selector:
    service: kafka-service
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: kafka-service
  name: kafka-service
spec:
  replicas: 1
  selector:
    matchLabels:
      service: kafka-service
  template:
    metadata:
      labels:
        service: kafka-service
    spec:
      containers:
      - image: confluentinc/cp-kafka:latest
        name: kafka-service
        imagePullPolicy: Always
        ports:
        - containerPort: 29092
        env:
        - name: KAFKA_BROKER_ID
          valueFrom:
            configMapKeyRef:
              name: kafka-env
              key: KAFKA_BROKER_ID
        - name: KAFKA_ZOOKEEPER_CONNECT
          valueFrom:
            configMapKeyRef:
              name: kafka-env
              key: KAFKA_ZOOKEEPER_CONNECT
        - name: KAFKA_ADVERTISED_LISTENERS
          valueFrom:
            configMapKeyRef:
              name: kafka-env
              key: KAFKA_ADVERTISED_LISTENERS
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          valueFrom:
            configMapKeyRef:
              name: kafka-env
              key: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          valueFrom:
            configMapKeyRef:
              name: kafka-env
              key: KAFKA_INTER_BROKER_LISTENER_NAME
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          valueFrom:
            configMapKeyRef:
              name: kafka-env
              key: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
        - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
          valueFrom:
            configMapKeyRef:
              name: kafka-env
              key: KAFKA_AUTO_CREATE_TOPICS_ENABLE
        - name: KAFKA_CFG_LISTENERS
          valueFrom:
            configMapKeyRef:
              name: kafka-env
              key: KAFKA_CFG_LISTENERS
        - name: ALLOW_PLAINTEXT_LISTENER
          valueFrom:
            configMapKeyRef:
              name: kafka-env
              key: ALLOW_PLAINTEXT_LISTENER
      restartPolicy: Always