apiVersion: v1
kind: Service
metadata:
  labels:
    service: zookeeper-service
  name: zookeeper-service
spec:
  ports:
  - port: 2181
  selector:
    service: zookeeper-service
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: zookeeper-service
  name: zookeeper-service
spec:
  replicas: 1
  selector:
    matchLabels:
      service: zookeeper-service
  template:
    metadata:
      labels:
        service: zookeeper-service
    spec:
      containers:
      - image: confluentinc/cp-zookeeper:latest
        name: zookeeper-service
        imagePullPolicy: Always
        ports:
        - containerPort: 2181
        env:
        - name: ZOOKEEPER_CLIENT_PORT
          valueFrom:
            configMapKeyRef:
              name: kafka-env
              key: ZOOKEEPER_CLIENT_PORT
        - name: ZOOKEEPER_TICK_TIME
          valueFrom:
            configMapKeyRef:
              name: kafka-env
              key: ZOOKEEPER_TICK_TIME
      restartPolicy: Always
